config/routes.rb
Ecoit::Application.routes.draw do

  get "index" => 'pages#index'
  get "help" => 'pages#help'
  get 'assets' => 'assets#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"
  delete 'logout' => "sessions#destroy"

  resources :users, except: :show
  resources :servers
  resources :softwares
  resources :network_devices
  resources :systems
  

    root 'pages#index'

end

app/models/software.rb
class Software < ActiveRecord::Base
	belongs_to :user
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)
    @software.user_id = current_user.id

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render action: 'show', status: :created, location: @software }
      else
        format.html { render action: 'new' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :kind, :sn, :service_expired_day, :function, :remark, :user_id)
    end
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= form_for @software, html: { class: "uk-form" } do |f| %>

  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>

      <ul>
      <% @software.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :name %>
      <%= f.text_field :name, class: "uk-width-1-1", placeholder: "Software name" %>
    </div>
    <div class="uk-width-medium-1-4">
      <%= f.label :kind %>
      <%= f.text_field :kind, class: "uk-width-1-1", placeholder: "Software kind" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :sn, "SN" %>
      <%= f.text_field :sn, class: "uk-width-1-1", placeholder: "Serial number" %>
    </div>
    <div class="uk-width-medium-1-4">
      <%= f.label :service_expired_day %>
      <%= f.text_field :service_expired_day, class: "uk-width-1-1", placeholder: "yyyy-mm-dd" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-2-3">
      <%= f.label :function %>
      <%= f.text_area :function, class: "uk-width-1-1", rows: 5, placeholder: "Let's know what the software work for" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-2-3">
      <%= f.label :remark %>
      <%= f.text_area :remark, class: "uk-width-1-1", rows: 5, placeholder: "Some remark optional" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-2">
      <%= f.submit class: "uk-button uk-button-large uk-button-primary" %>
      <%= link_to 'Back', softwares_path, class: "uk-button uk-button-link" %>
    </div>
  </div>

<% end %>

app/views/softwares/_software.html.erb
<tr>
  <td><%= software.name %></td>
  <td class="uk-hidden-small"><%= software.kind %></td>
  <td class="uk-hidden-small"><%= software.sn %></td>
  <td class="uk-hidden-small"><%= software.service_expired_day %></td>
  <td>
    <%= link_to software, class: "uk-button uk-button-success uk-button-mini" do %>
      <i class="uk-icon-eye"></i>
    <% end %>
    <%= link_to edit_software_path(software), class: "uk-button uk-button-primary uk-button-mini" do %>
      <i class="uk-icon-pencil"></i>
    <% end %>
    <%= link_to software, method: :delete, data: { confirm: "Are you sure to delete software #{software.name} ?" }, class: "uk-button uk-button-danger uk-button-mini" do %>
      <i class="uk-icon-trash-o"></i>
    <% end %>
  </td>
</tr>

app/views/softwares/edit.html.erb
<% provide :title, "Editing software" %>

<h1>Editing software</h1>

<hr>

<%= render 'form' %>

app/views/softwares/index.html.erb
<%= provide :title, "Listing softwares" %>

<div id="users-list" class="uk-container uk-container-center">
  
  <div class="uk-grid">
    
    <div class="eco-sidebar uk-width-medium-1-4">

      <%= render 'assets/sidebar' %>

    </div>

    <div class="eco-main uk-width-medium-3-4">

      <h1>Listing softwares</h1>

      <table class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
        <thead>
          <tr>
            <th>Name</th>
            <th class="uk-hidden-small">Kind</th>
            <th class="uk-hidden-small">SN</th>
            <th class="uk-hidden-small">Service expired day</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          <%= render @softwares %>
        </tbody>
      </table>

      <br>

      <%= link_to new_software_path, class: "uk-button uk-button-large uk-button-success" do %>
        New Software <i class="uk-icon-arrow-circle-right"></i>
      <% end %>

    </div>

  </div>

</div>

app/views/softwares/new.html.erb
<% provide :title, "New software" %>

<h1>New software</h1>

<hr>

<%= render 'form' %>

app/views/softwares/show.html.erb
<%= provide :title, "Software-#{@software.name}" %>

<h1>Show software</h1>

<hr>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Software Name</dt>
    <dd><%= @software.name %></dd>
  </div>
  <div class="uk-width-medium-1-4">  
    <dt>Operation system</dt>
    <dd><%= @software.kind %></dd>
  </div>
</dl>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Serial number</dt>
    <dd><%= @software.sn %></dd>
  </div>
  <div class="uk-width-medium-1-4">  
    <dt>Service expired day</dt>
    <dd><%= @software.service_expired_day %></dd>
  </div>
</dl>

<% if @software.function.present? %>
  <dl class="uk-grid">
    <div class="uk-width-medium-1-2">
      <dt>Function</dt>
      <dd><%= @software.function %></dd>
    </div>
  </dl>
<% end %>

<% if @software.remark.present? %>
  <dl class="uk-grid">
    <div class="uk-width-medium-1-2">
      <dt>Remark</dt>
      <dd><%= @software.remark %></dd>
    </div>
  </dl>
<% end %>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Create by</dt>
    <dd><%= @software.user.username %></dd>
  </div>
</dl>

<br>

<%= link_to edit_software_path(@software), class: "uk-button uk-button-success" do %>
  Edit <i class="uk-icon-pencil"></i>
<% end %>
<%= link_to 'Back', softwares_path, class: "uk-button uk-button-link" %>