config/routes.rb
Ecoit::Application.routes.draw do

  get "index" => 'pages#index'
  get "help" => 'pages#help'
  get 'assets' => 'assets#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"
  delete 'logout' => "sessions#destroy"

  resources :users, except: :show
  resources :servers
  resources :softwares
  resources :network_devices
  resources :systems
  

    root 'pages#index'

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	def index
	end
end

app/helpers/assets_helper.rb
module AssetsHelper
	def servers_qty
		Server.count
	end
	def softwares_qty
		Software.count
	end
	def network_devices_qty
		NetworkDevice.count
	end
end

app/views/assets/_sidebar.html.erb
<ul class="uk-nav">

	<li>
  	<%= render 'share/search' %>
  </li>
  <li class="uk-nav-header">Assets</li>
  <li id="servers"><a href="<%= servers_path %>">Servers</a></li>
  <li id="softwares"><a href="<%= softwares_path %>">Softwares</a></li>
  <li id="network-devices"><a href="<%= network_devices_path %>">Netword devices</a></li>
  <li id="systems"><a href="<%= systems_path %>">Systems</a></li>

</ul>

app/views/assets/index.html.erb
<% provide :title, "Listing assets" %>

<div id="users-list" class="uk-container uk-container-center">
	
	<div class="uk-grid">
    
    <div class="eco-sidebar uk-width-medium-1-4">

      <%= render 'assets/sidebar' %>

    </div>


    <div class="eco-main uk-width-medium-3-4">
			<h1><i class="uk-icon-gears"></i> Listing assets</h1>
			<table class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
				<thead>
					<tr>
						<th>Kind</th>
						<th>Qty</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Server</td>
						<td><%= servers_qty %></td>
					</tr>
					<tr>
						<td>Software</td>
						<td><%= softwares_qty %></td>
					</tr>
					<tr>
						<td>Network Device</td>
						<td><%= network_devices_qty %></td>
					</tr>
				</tbody>
			</table>
    </div>
	</div>
</div>