config/routes.rb
Ecoit::Application.routes.draw do

  get "index" => 'pages#index'
  get "help" => 'pages#help'
  get 'assets' => 'assets#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"
  delete 'logout' => "sessions#destroy"

  resources :users, except: :show
  resources :servers
  resources :softwares
  resources :network_devices
  resources :systems
  

    root 'pages#index'

end

app/models/network_device.rb
class NetworkDevice < ActiveRecord::Base
	belongs_to :user
end

app/controllers/network_devices_controller.rb
class NetworkDevicesController < ApplicationController
  before_action :set_network_device, only: [:show, :edit, :update, :destroy]

  # GET /network_devices
  # GET /network_devices.json
  def index
    @network_devices = NetworkDevice.all
  end

  # GET /network_devices/1
  # GET /network_devices/1.json
  def show
  end

  # GET /network_devices/new
  def new
    @network_device = NetworkDevice.new
  end

  # GET /network_devices/1/edit
  def edit
  end

  # POST /network_devices
  # POST /network_devices.json
  def create
    @network_device = NetworkDevice.new(network_device_params)
    @network_device.user_id = current_user.id

    respond_to do |format|
      if @network_device.save
        format.html { redirect_to @network_device, notice: 'Network device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @network_device }
      else
        format.html { render action: 'new' }
        format.json { render json: @network_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /network_devices/1
  # PATCH/PUT /network_devices/1.json
  def update
    respond_to do |format|
      if @network_device.update(network_device_params)
        format.html { redirect_to @network_device, notice: 'Network device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @network_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /network_devices/1
  # DELETE /network_devices/1.json
  def destroy
    @network_device.destroy
    respond_to do |format|
      format.html { redirect_to network_devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network_device
      @network_device = NetworkDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_device_params
      params.require(:network_device).permit(:name, :ip, :kind, :place, :position, :sn, :service_expired_day, :function, :remark, :user_id)
    end
end

app/helpers/network_devices_helper.rb
module NetworkDevicesHelper
end

app/views/network_devices/_form.html.erb
<%= form_for @network_device, html: { class: "uk-form" } do |f| %>
  <% if @network_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@network_device.errors.count, "error") %> prohibited this network_device from being saved:</h2>

      <ul>
      <% @network_device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :name %>
      <%= f.text_field :name, class: "uk-width-1-1", placeholder: "Network device name" %>
    </div>
    <div class="uk-width-medium-1-4">
      <%= f.label :kind %>
      <%= f.text_field :kind, class: "uk-width-1-1", placeholder: "Network device kind" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :ip, :IP %>
      <%= f.text_field :ip, class: "uk-width-1-1", placeholder: "IP Address" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :place %>
      <%= f.text_field :place, class: "uk-width-1-1", placeholder: "Where is the network device" %>
    </div>
    <div class="uk-width-medium-1-4">
      <%= f.label :position %>
      <%= f.text_field :position, class: "uk-width-1-1", placeholder: "Network device position" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-4">
      <%= f.label :sn, "SN" %>
      <%= f.text_field :sn, class: "uk-width-1-1", placeholder: "Serial Number" %>
    </div>
    <div class="uk-width-medium-1-4">
      <%= f.label :service_expired_day %>
      <%= f.date_field :service_expired_day, class: "uk-width-1-1", placeholder: "yyyy-mm-dd" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-2-3">
      <%= f.label :function %>
      <%= f.text_area :function, class: "uk-width-1-1", rows: 5, placeholder: "Let's know what the network device work for" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-2-3">
      <%= f.label :remark %>
      <%= f.text_area :remark, class: "uk-width-1-1", rows: 5, placeholder: "Some remark optional" %>
    </div>
  </div>

  <div class="uk-grid">
    <div class="uk-width-medium-1-2">
      <%= f.submit class: "uk-button uk-button-large uk-button-primary" %>
      <%= link_to 'Back', servers_path, class: "uk-button uk-button-link" %>
    </div>
  </div>

<% end %>

app/views/network_devices/_network_device.html.erb
<tr>
  <td><%= network_device.name %></td>
  <td class="uk-hidden-small"><%= network_device.kind %></td>
  <td class="uk-hidden-small"><%= network_device.ip %></td>
  <td class="uk-hidden-small"><%= network_device.sn %></td>
  <td class="uk-hidden-small"><%= network_device.service_expired_day %></td>
  <td>
    <%= link_to network_device, class: "uk-button uk-button-success uk-button-mini" do %>
      <i class="uk-icon-eye"></i>
    <% end %>
    <%= link_to edit_network_device_path(network_device), class: "uk-button uk-button-primary uk-button-mini" do %>
      <i class="uk-icon-pencil"></i>
    <% end %>
    <%= link_to network_device, method: :delete, data: { confirm: "Are you sure to delete network_device #{network_device.name} ?" }, class: "uk-button uk-button-danger uk-button-mini" do %>
      <i class="uk-icon-trash-o"></i>
    <% end %>
  </td>
</tr>

app/views/network_devices/edit.html.erb
<% provide :title, "Editing network device" %>

<h1>Editing network device</h1>

<hr>

<%= render 'form' %>

app/views/network_devices/index.html.erb
<%= provide :title, "Listing network_device" %>

<div id="users-list" class="uk-container uk-container-center">
  
  <div class="uk-grid">
    
    <div class="eco-sidebar uk-width-medium-1-4">

      <%= render 'assets/sidebar' %>

    </div>

    <div class="eco-main uk-width-medium-3-4">

      <h1>Listing network_device</h1>

      <table class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
        <thead>
          <tr>
          <th>Name</th>
          <th class="uk-hidden-small">Kind</th>
          <th class="uk-hidden-small">IP</th>
          <th class="uk-hidden-small">SN</th>
          <th class="uk-hidden-small">Service expired day</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <%= render @network_devices %>
      </tbody>
    </table>

      <br>

      <%= link_to new_network_device_path, class: "uk-button uk-button-large uk-button-success" do %>
        New network_device <i class="uk-icon-arrow-circle-right"></i>
      <% end %>

    </div>

  </div>

</div>

app/views/network_devices/new.html.erb
<% provide :title, "New network device" %>


<h1>New network device</h1>

<hr>

<%= render 'form' %>

app/views/network_devices/show.html.erb
<%= provide :title, "network device | #{@network_device.name}" %>

<h1>Show network device</h1>

<hr>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Network device Name</dt>
    <dd><%= @network_device.name %></dd>
  </div>
  <div class="uk-width-medium-1-4">  
    <dt>Operation kind</dt>
    <dd><%= @network_device.kind %></dd>
  </div>
</dl>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>IP Address</dt>
    <dd><%= @network_device.ip %></dd>
  </div>
</dl>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Place</dt>
    <dd><%= @network_device.place %></dd>
  </div>
  <div class="uk-width-medium-1-4">  
    <dt>Position</dt>
    <dd><%= @network_device.position %></dd>
  </div>
</dl>

<% if @network_device.function.present? %>
  <dl class="uk-grid">
    <div class="uk-width-medium-1-2">
      <dt>Function</dt>
      <dd><%= @network_device.function %></dd>
    </div>
  </dl>
<% end %>

<% if @network_device.remark.present? %>
  <dl class="uk-grid">
    <div class="uk-width-medium-1-2">
      <dt>Remark</dt>
      <dd><%= @network_device.remark %></dd>
    </div>
  </dl>
<% end %>

<dl class="uk-grid">
  <div class="uk-width-medium-1-4">
    <dt>Create by</dt>
    <dd><%= @network_device.user.username %></dd>
  </div>
</dl>

<br>

<%= link_to edit_network_device_path(@network_device), class: "uk-button uk-button-success" do %>
  Edit <i class="uk-icon-pencil"></i>
<% end %>
<%= link_to 'Back', network_devices_path, class: "uk-button uk-button-link" %>