config/routes.rb
Ecoit::Application.routes.draw do

  get "index" => 'pages#index'
  get "help" => 'pages#help'
  get 'assets' => 'assets#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => "sessions#new"
  delete 'logout' => "sessions#destroy"

  resources :users, except: :show
  resources :servers
  resources :softwares
  resources :network_devices
  resources :systems
  

    root 'pages#index'

end

app/views/layouts/_footer.html.erb
<div class="uk-container uk-container-center uk-text-center">

    <span>Designed by</span>&nbsp;<a href="https://github.com/vincentjiang/" target="_blank"><strong>VincentJiang</strong></a>

    <ul class="tm-subnav uk-subnav">
        <li><a href="https://github.com/vincentjiang/ecoit" target="_blank"><i class="uk-icon-github"></i> GitHub</a></li>
        <li><a href="mailto:jxs471494539@gmail.com?subject=ECO IT System"><i class="uk-icon-envelope"></i> Contact</a></li>
        <li data-uikit-version=""></li>
    </ul>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="uk-alert uk-alert-<%= name == :notice ? "success" : "danger" %>"  data-uk-alert >
    	<a href="" class="uk-alert-close uk-close"></a>
      <%= content_tag :div, msg, :id => "flash_#{name}", class: "uk-text-center" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav id="#top" class="tm-navbar uk-navbar uk-navbar-attached">
  <div class="uk-container uk-container-center">

    <a class="uk-navbar-brand uk-hidden-small" href="<%= root_path %>"><i class="uk-icon-home"></i> ECO IT System</a>

    <ul class="uk-navbar-nav uk-hidden-small">
      <li><%= link_to 'Assets', assets_path %></li>
      <% if current_user && current_user.admin %>
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
      <li><a href="<%= help_path %>">Help</a></li>
    </ul>

    <div class="uk-navbar-flip">
        <ul class="uk-navbar-nav">
            
            <% if session[:user_id] %>
              <li>
                <%= link_to edit_user_path(current_user), "data-uk-tooltip" => "pos:'bottom'", title: "#{current_user.username}" do %>
                  <i class="uk-icon-user"></i>
                <% end %>
              </li>
              <li>
                <%= link_to logout_path, method: :delete, data: { confirm: "Are you sure ?" }, "data-uk-tooltip" => "pos: 'bottom'", title: "Logout" do %>
                  <i class="uk-icon-power-off"></i>
                <% end %>
              </li>
            <% else %>
              <li><a href="<%= login_path %>" data-uk-tooltip="pos:'bottom'" title="Login">Login <i class="uk-icon-sign-in"></i></a></li>
            <% end %>
        </ul>
    </div>

    <a href="#eco-offcanvas" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas></a>

    <a class="uk-navbar-brand uk-visible-small" href="/"><i class="uk-icon-home"></i></a>

  </div>
</nav>


<!-- uk-offcanvas -->
<div id="eco-offcanvas" class="uk-offcanvas">

  <div class="uk-offcanvas-bar">

      <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon" data-uk-nav="{ multiple: true }">
          <li class="uk-parent"><a href="#">Documentation</a>
              <div style="overflow: hidden; height: 0px; position: relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/documentation_get-started.html">Get started</a></li>
                  <li><a href="docs/documentation_how-to-customize.html">How to customize</a></li>
                  <li><a href="docs/documentation_layouts.html">Layout examples</a></li>
                  <li><a href="docs/components.html">Components</a></li>
                  <li><a href="docs/addons.html">Add-ons</a></li>
                  <li><a href="docs/documentation_project-structure.html">Project structure</a></li>
                  <li><a href="docs/documentation_create-a-theme.html">Create a theme</a></li>
                  <li><a href="docs/documentation_create-a-style.html">Create a style</a></li>
                  <li><a href="docs/documentation_customizer-json.html">Customizer.json</a></li>
              </ul></div>
          </li>
          <li class="uk-nav-header">Components</li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-wrench"></i> Defaults</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/normalize.html">Normalize</a></li>
                  <li><a href="docs/base.html">Base</a></li>
                  <li><a href="docs/print.html">Print</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-th-large"></i> Layout</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/grid.html">Grid</a></li>
                  <li><a href="docs/panel.html">Panel</a></li>
                  <li><a href="docs/article.html">Article</a></li>
                  <li><a href="docs/comment.html">Comment</a></li>
                  <li><a href="docs/utility.html">Utility</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-bars"></i> Navigations</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/nav.html">Nav</a></li>
                  <li><a href="docs/navbar.html">Navbar</a></li>
                  <li><a href="docs/subnav.html">Subnav</a></li>
                  <li><a href="docs/breadcrumb.html">Breadcrumb</a></li>
                  <li><a href="docs/pagination.html">Pagination</a></li>
                  <li><a href="docs/tab.html">Tab</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-check"></i> Elements</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/list.html">List</a></li>
                  <li><a href="docs/description-list.html">Description list</a></li>
                  <li><a href="docs/table.html">Table</a></li>
                  <li><a href="docs/form.html">Form</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-folder-open"></i> Common</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/button.html">Button</a></li>
                  <li><a href="docs/icon.html">Icon</a></li>
                  <li><a href="docs/close.html">Close</a></li>
                  <li><a href="docs/badge.html">Badge</a></li>
                  <li><a href="docs/alert.html">Alert</a></li>
                  <li><a href="docs/thumbnail.html">Thumbnail</a></li>
                  <li><a href="docs/overlay.html">Overlay</a></li>
                  <li><a href="docs/progress.html">Progress</a></li>
                  <li><a href="docs/search.html">Search</a></li>
                  <li><a href="docs/text.html">Text</a></li>
                  <li><a href="docs/animation.html">Animation</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#"><i class="uk-icon-magic"></i> JavaScript</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/dropdown.html">Dropdown</a></li>
                  <li><a href="docs/modal.html">Modal</a></li>
                  <li><a href="docs/offcanvas.html">Off-canvas</a></li>
                  <li><a href="docs/switcher.html">Switcher</a></li>
                  <li><a href="docs/toggle.html">Toggle</a></li>
                  <li><a href="docs/tooltip.html">Tooltip</a></li>
                  <li><a href="docs/scrollspy.html">Scrollspy</a></li>
                  <li><a href="docs/smooth-scroll.html">Smooth scroll</a></li>
              </ul></div>
          </li>
          <li class="uk-parent"><a href="#">Add-ons</a>
              <div style="overflow:hidden;height:0;position:relative;"><ul class="uk-nav-sub">
                  <li><a href="docs/addons_markdownarea.html">Markdown area</a></li>
                  <li><a href="docs/addons_sortable.html">Sortable</a></li>
                  <li><a href="docs/addons_datepicker.html">Datepicker</a></li>
                  <li><a href="docs/addons_timepicker.html">Timepicker</a></li>
                  <li><a href="docs/addons_sticky.html">Sticky</a></li>
                  <li><a href="docs/addons_notify.html">Notify</a></li>
                  <li><a href="docs/addons_form-password.html">Form password</a></li>
                  <li><a href="docs/addons_form-file.html">Form file</a></li>
              </ul></div>
          </li>
      </ul>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8" />

	  <%= favicon_link_tag 'towngas_logo.jpg' %>

	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	  <title><%= content_for?(:title) ? yield(:title) : "ECO IT System" %></title>

	  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ecoit" %>">
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<div class="header">
			<%= render 'layouts/navigation' %>
		</div>
		
		<div class="content">
			<div class="uk-container uk-container-center">

				<%= render 'layouts/messages' %>

				<div class="main">
					<%= yield %>
				</div>

				<a href="#top" class="uk-icon-button go-top" data-uk-smooth-scroll>
					<i class="uk-icon-arrow-up"></i>
				</a>
				
			</div>
		</div>

		<%= debug(params) if Rails.env.development? %>
			
		<div class="footer">
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>